name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master    

env:
  binary: bevy-game

jobs:
  # Build for wasm
  release-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0

      - run: trunk build --release

      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "\"/"
          replace: "\"/${{ github.workspace }}/"
          include: ./dist/index.html

      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "'/"
          replace: "'/${{ github.workspace }}/"
          include: ./dist/index.html

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
